#! /bin/sh
### BEGIN INIT INFO
# Provides:          my-bindfs-mounts
# Required-Start:    $local_fs $remote_fs vboxdrv vboxnet
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create custom bindings
# Description:       Create custom bindings of folders into other place
### END INIT INFO

# Author: Daniel Dalgo <dalguete@gmail.com>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Create custom bindings"
NAME=my-bindfs-mounts
BINDFS=/usr/bin/bindfs
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$BINDFS" ] || exit 0

# Read configuration variable file if it is present
DATA=''
if [ -r /etc/default/$NAME ]; then
  while read line    
  do  
    my_line=`echo $line | grep -e ^# -v`

    if [ -n "$my_line" ]; then
	DATA="${DATA}${my_line}\n"
    fi
  done </etc/default/$NAME
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	mounts=`mount -t fuse.bindfs | wc -l`

	if [ "$mounts" != "0" ]; then
	  echo "$DESC" was already executed.
	  return 2
	fi

	exists=0
	$( echo $DATA > /tmp/my-bindfs-mounts )

	while read line    
	do  
	  if [ -n "$line" ]; then
  	    exists=1

	    eval "$BINDFS $line 2> /tmp/my-bindfs-mounts-error"
	  fi
	done </tmp/my-bindfs-mounts

	rm /tmp/my-bindfs-mounts

	if [ "$exists" = "0" ]; then
   	  echo "$DESC" could not be started. Config file must contain data.
	  return 2
	fi

	if [ -f /tmp/my-bindfs-mounts-error ]; then
	  nLines=`cat /tmp/my-bindfs-mounts-error | wc -l | awk '{print $1'}`

	  if [ "$nLines" != "0" ]; then
     	    echo "$DESC could not be started (maybe incomplete activations)." `cat /tmp/my-bindfs-mounts-error`
  	    rm /tmp/my-bindfs-mounts-error
	    return 2
	  fi
 	fi

	echo "$DESC" started or resumed.
	return 0
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	mounts=`mount -t fuse.bindfs | wc -l`

	if [ "$mounts" = "0" ]; then
	  echo "$DESC" is already stopped.
	  return 1
	fi

	umount -t fuse.bindfs -a >/dev/null
	echo "$DESC" stopped.
	return 0	
}

#
# Display "State" field from showinfo action
#
do_status()
{
	mount -t fuse.bindfs > /tmp/my-bindfs-mounts-status
	cat /tmp/my-bindfs-mounts-status
 	mounts=$( grep -o "bindfs on" /tmp/my-bindfs-mounts-status | wc -l )
	rm /tmp/my-bindfs-mounts-status
	echo "..." $mounts "mount(s) ..."
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  status)
	do_status
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac
