#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          my-bindfs-mounts
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create custom bindings
# Description:       Create custom bindings of folders into other place
### END INIT INFO

# Author: Daniel Dalgo <dalguete@gmail.com>
#
# Do NOT "set -e"
DESC="Create custom bindings"
NAME=my-bindfs-mounts
DAEMON=/usr/bin/$NAME

#
# Function that performs the actual service init.
#
# Return
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start_cmd_override()
{
	# Count mounts
	local mounts=`$DAEMON -l | wc -l`

	if (( $mounts )); then
	  echo "$DESC" was already executed.

	  return 1
	fi

  # Mount all from config file
	local errors="$($DAEMON --load-from-file /etc/default/$NAME 2>&1)"

  if [ -n "$errors" ]; then
		echo "$DESC could not be started (maybe incomplete activations)..."
		echo $errors

		return 2
  fi

	# Message
	echo "$DESC" started.

	return 0
}

#
# Function that performs the actual service stop.
#
# Return
#   0 if daemon has been stopped
#   1 if daemon was already stopped
#   2 if daemon could not be stopped
#   other if a failure occurred
do_stop_cmd_override()
{
	# Count mounts
	local mounts=`$DAEMON -l | wc -l`

	if (( !$mounts )); then
	  echo "$DESC" is already stopped.

	  return 1
	fi

	# Umount all
	$DAEMON --umount-all

	# Message
	echo "$DESC" stopped.

	return 0	
}

#
# Function that performs the actual status shown of the service.
#
do_status_override()
{
	# Count mounts
 	local mounts=$( $NAME -l | wc -l )

	# Message
	echo "..." $mounts "bindfs mount(s) ..."
}

