#!/bin/sh

#!/bin/sh

########################
## 'Package checkings ##
########################

TO_INSTALL=

# Check 'bash' package is installed in host.
echo "Checking 'bash' package is available..."
which bash
ERROR_CODE=$?

if [ $ERROR_CODE != 0 ]; then
  TO_INSTALL="$TO_INSTALL bash"
fi

# Check 'bindfs' package is installed in host.
echo "Checking 'bindfs' package is available..."
which bindfs
ERROR_CODE=$?

if [ $ERROR_CODE != 0 ]; then
  TO_INSTALL="$TO_INSTALL bindfs"
fi

############################
## 'Package installations ##
############################

if [ -z "$TO_INSTALL" ]; then
  echo "Ol Korrect :P"
  exit
fi

# Updating packages.
echo "Installing missing packages..."
apt-get update
apt-get install -y "$TO_INSTALL"
ERROR_CODE=$?

if [ $ERROR_CODE != 0 ]; then
  echo "Error in installation!" >&2
  exit $ERROR_CODE
fi

###########################
## 'Package re-checkings ##
###########################

# Check 'bash' package is installed in host.
echo "Checking 'bash' package is available..."
which bash
ERROR_CODE=$?

if [ $ERROR_CODE != 0 ]; then
  echo "Package 'bash' still not available!" >&2
  exit $ERROR_CODE
fi

# Check 'bindfs' package is installed in host.
echo "Checking 'bindfs' package is available..."
which bindfs
ERROR_CODE=$?

if [ $ERROR_CODE != 0 ]; then
  echo "Package 'bindfs' still not available!" >&2
  exit $ERROR_CODE
fi
